import { api, apiBaseUrl, isMockMode } from "./apiClient";
import type { AdminChangeRequest, Judge, TeamGenerationConfig, RequestStatus, Role } from "../types";
import { readStorage, writeStorage } from "./storage";

type BackendJudge = { id: string; name: string; expertise: string; handle: string; photoUrl?: string | null; status: "ACTIVE" | "INACTIVE"; createdAt: string };
export type HackathonSummary = { id: string; name: string; description?: string; theme?: string; startDate: string; endDate: string; maxTeamSize: number; minTeamSize: number };
export type TeamMember = { id: string; studentId: string; name: string; rollNumber: string; role: string; position: string };
export type HackathonTeam = { id: string; teamName: string; leaderId: string; status: string; position: number; score: number; teamMembers: TeamMember[] };
const mockHackathons: HackathonSummary[] = [{ id: "hackathon-demo", name: "Kortex AI Innovation Hackathon", description: "Build useful AI and data products for campus life.", theme: "Applied AI", startDate: "2026-10-10", endDate: "2026-10-12", minTeamSize: 2, maxTeamSize: 4 }];
const mockJudges: Judge[] = [{ id: "judge-demo", name: "Dr. Meera Shah", expertise: "Machine Learning Researcher", handle: "meera-shah", photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80", status: "active", createdAt: new Date().toISOString() }];
const mockTeamsKey = "kortex-demo-hackathon-teams";
const mockMyTeamKey = "kortex-demo-my-team";
const mockStudents = [{ id: "student-demo", name: "Aarav Mehta", rollNumber: "2420080001" }, { id: "student-2", name: "Ananya Rao", rollNumber: "2420080002" }, { id: "student-3", name: "Rahul Verma", rollNumber: "2420080003" }, { id: "student-4", name: "Ishita Reddy", rollNumber: "2420080004" }];
type BackendRequest = { id: string; requesterId: string; requesterRole?: "STUDENT" | "FACULTY" | "MOD" | "ADMIN"; description: string; status: "PENDING" | "APPROVED" | "REJECTED"; createdAt: string };

const mapJudge = (judge: BackendJudge): Judge => ({ id: judge.id, name: judge.name, expertise: judge.expertise, handle: judge.handle, photo: judge.photoUrl ? `${apiBaseUrl.replace(/\/api$/, "")}${judge.photoUrl}` : undefined, status: judge.status === "ACTIVE" ? "active" : "inactive", createdAt: judge.createdAt });
const mapRequest = (request: BackendRequest): AdminChangeRequest => ({ id: request.id, requesterRole: (request.requesterRole || "STUDENT").toLowerCase() as Role, message: request.description, status: request.status.charAt(0) + request.status.slice(1).toLowerCase() as RequestStatus, createdAt: request.createdAt });
export async function listHackathons() { if (isMockMode) return mockHackathons; const result = await api<HackathonSummary[] | { hackathons: HackathonSummary[] }>("/hackathons"); return Array.isArray(result) ? result : result.hackathons; }
export async function listJudges(hackathonId: string) { if (isMockMode) return readStorage<Judge[]>(`kortex-demo-judges-${hackathonId}`, mockJudges); return (await api<BackendJudge[]>(`/hackathons/${hackathonId}/judges`)).map(mapJudge); }
export async function listTeams(hackathonId: string) { if (isMockMode) return readStorage<HackathonTeam[]>(`${mockTeamsKey}-${hackathonId}`, []); return api<HackathonTeam[]>(`/hackathons/${hackathonId}/teams`); }
export async function getMyTeam(hackathonId: string) { if (isMockMode) return readStorage<HackathonTeam | null>(`${mockMyTeamKey}-${hackathonId}`, null); return api<HackathonTeam | null>(`/hackathons/${hackathonId}/my-team`); }
export async function findStudent(identifier: string) { if (isMockMode) { const value = identifier.trim().toLowerCase(); return mockStudents.find((student) => student.rollNumber.toLowerCase() === value || student.name.toLowerCase() === value) || null; } return api<{ id: string; name: string; rollNumber: string }>(`/hackathons/students/search?q=${encodeURIComponent(identifier)}`); }
export async function createMyTeam(hackathonId: string, teamName: string, leader: { id: string; name: string; rollNumber: string }) { if (isMockMode) { const team: HackathonTeam = { id: crypto.randomUUID(), teamName, leaderId: leader.id, status: "Registered", position: 0, score: 0, teamMembers: [{ id: crypto.randomUUID(), studentId: leader.id, name: leader.name, rollNumber: leader.rollNumber, role: "Leader", position: "Team lead" }] }; writeStorage(`${mockMyTeamKey}-${hackathonId}`, team); return team; } return api<HackathonTeam>(`/hackathons/${hackathonId}/teams`, { method: "POST", body: JSON.stringify({ teamName, leaderId: leader.id }) }); }
export async function addTeamMember(hackathonId: string, teamId: string, student: { id: string; name: string; rollNumber: string }) { if (isMockMode) { const team = await getMyTeam(hackathonId); if (!team) throw new Error("Create a team first."); if (team.teamMembers.some((member) => member.studentId === student.id)) throw new Error("Student is already in this team."); const updated = { ...team, teamMembers: [...team.teamMembers, { id: crypto.randomUUID(), studentId: student.id, name: student.name, rollNumber: student.rollNumber, role: "Member", position: "Contributor" }] }; writeStorage(`${mockMyTeamKey}-${hackathonId}`, updated); return updated; } return api<HackathonTeam>(`/hackathons/${hackathonId}/teams/${teamId}/members`, { method: "POST", body: JSON.stringify({ studentId: student.id }) }); }
export async function updateMyTeam(hackathonId: string, teamId: string, teamName: string) { if (isMockMode) { const team = await getMyTeam(hackathonId); if (!team) throw new Error("Team not found."); const updated = { ...team, teamName }; writeStorage(`${mockMyTeamKey}-${hackathonId}`, updated); return updated; } return api<HackathonTeam>(`/hackathons/${hackathonId}/teams/${teamId}`, { method: "PATCH", body: JSON.stringify({ teamName }) }); }
export async function createJudge(hackathonId: string, input: { name: string; expertise: string; handle: string; photo: File }) { if (isMockMode) { const photo = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Unable to read image.")); reader.readAsDataURL(input.photo); }); const judge: Judge = { id: crypto.randomUUID(), name: input.name, expertise: input.expertise, handle: input.handle, photo, status: "active", createdAt: new Date().toISOString() }; writeStorage(`kortex-demo-judges-${hackathonId}`, [...await listJudges(hackathonId), judge]); return judge; } const form = new FormData(); form.append("name", input.name); form.append("expertise", input.expertise); form.append("handle", input.handle); form.append("photo", input.photo); return mapJudge(await api<BackendJudge>(`/hackathons/${hackathonId}/judges`, { method: "POST", body: form })); }
export async function deleteJudge(hackathonId: string, judgeId: string) { if (isMockMode) { writeStorage(`kortex-demo-judges-${hackathonId}`, (await listJudges(hackathonId)).filter((judge) => judge.id !== judgeId)); return; } return api<void>(`/hackathons/${hackathonId}/judges/${judgeId}`, { method: "DELETE" }); }
export async function submitHackathonRequest(hackathonId: string, description: string) { if (isMockMode) { const request: AdminChangeRequest = { id: crypto.randomUUID(), requesterRole: "student", message: description, status: "Pending", createdAt: new Date().toISOString() }; writeStorage("kortex-demo-requests", [...readStorage<AdminChangeRequest[]>("kortex-demo-requests", []), request]); return request; } return api<AdminChangeRequest>(`/hackathons/${hackathonId}/change-requests`, { method: "POST", body: JSON.stringify({ type: "HACKATHON_UPDATE", description }) }); }
export async function listHackathonRequests() { if (isMockMode) return readStorage<AdminChangeRequest[]>("kortex-demo-requests", []).filter((request) => request.status === "Pending"); return (await api<BackendRequest[]>("/admin/hackathon-requests")).map(mapRequest); }
export async function reviewHackathonRequest(id: string, status: "APPROVED" | "REJECTED", reviewReason?: string) { if (isMockMode) { const next: RequestStatus = status === "APPROVED" ? "Approved" : "Rejected"; writeStorage("kortex-demo-requests", readStorage<AdminChangeRequest[]>("kortex-demo-requests", []).map((request) => request.id === id ? { ...request, status: next } : request)); return; } return api<AdminChangeRequest>(`/admin/hackathon-requests/${id}`, { method: "PATCH", body: JSON.stringify({ status, reviewReason }) }); }
export async function saveTeamGeneration(hackathonId: string, config: TeamGenerationConfig) { if (isMockMode) { const count = 8; const teams = Array.from({ length: Math.ceil(count / config.teamSize) }, (_, index) => ({ id: crypto.randomUUID(), teamName: `${config.teamPoolName} ${index + 1}`, leaderId: `demo-student-${index * config.teamSize + 1}`, status: "Generated", position: index + 1, score: 0, teamMembers: Array.from({ length: Math.max(0, Math.min(config.teamSize, count - index * config.teamSize)) }, (_, memberIndex) => ({ id: crypto.randomUUID(), studentId: `demo-student-${index * config.teamSize + memberIndex + 1}`, name: `Student ${index * config.teamSize + memberIndex + 1}`, rollNumber: `22DS${String(index * config.teamSize + memberIndex + 1).padStart(3, "0")}`, role: memberIndex === 0 ? "Leader" : "Member", position: memberIndex === 0 ? "Team lead" : "Contributor" })) })); writeStorage(`${mockTeamsKey}-${hackathonId}`, teams); return { ...config, generatedAt: new Date().toISOString(), teams }; } return api<{ teamPoolName: string; teamSize: number; generatedAt: string; teams: HackathonTeam[] }>(`/hackathons/${hackathonId}/generate-teams`, { method: "POST", body: JSON.stringify(config) }); }
