import { useEffect, useState } from "react";
import { CalendarDays, MapPin, Plus, Save, Search, Users } from "lucide-react";
import Card from "../../components/common/Card";
import Loading from "../../components/common/Loading";
import ProfileCard from "../../components/common/ProfileCard";
import StatusState from "../../components/common/StatusState";
import type { Judge } from "../../types";
import { addTeamMember, createMyTeam, findStudent, getMyTeam, listHackathons, listJudges, updateMyTeam, type HackathonSummary, type HackathonTeam } from "../../services/hackathonApi";

export default function HackathonWorkspacePage() {
  const [hackathons, setHackathons] = useState<HackathonSummary[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [judges, setJudges] = useState<Judge[]>([]);
  const [team, setTeam] = useState<HackathonTeam | null>(null);
  const [teamName, setTeamName] = useState("");
  const [updatedTeamName, setUpdatedTeamName] = useState("");
  const [studentSearch, setStudentSearch] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { (async () => { try { const items = await listHackathons(); setHackathons(items); if (items[0]) { setSelectedId(items[0].id); setJudges(await listJudges(items[0].id)); setTeam(await getMyTeam(items[0].id)); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load hackathons."); } finally { setLoading(false); } })(); }, []);
  const selected = hackathons.find((item) => item.id === selectedId);
  const switchHackathon = async (id: string) => { setSelectedId(id); setTeam(await getMyTeam(id)); setJudges(await listJudges(id)); setMessage(""); };
  const createTeam = async (event: React.FormEvent) => { event.preventDefault(); if (!selected || !teamName.trim()) return; try { const created = await createMyTeam(selected.id, teamName.trim(), { id: "student-demo", name: "Aarav Mehta", rollNumber: "2420080001" }); setTeam(created); setMessage("Team created successfully."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to create team."); } };
  const addMember = async () => { if (!selected || !team || !studentSearch.trim()) return; try { const student = await findStudent(studentSearch); if (!student) { setMessage("No student found with that name or roll number."); return; } setTeam(await addTeamMember(selected.id, team.id, student)); setStudentSearch(""); setMessage(`${student.name} added to your team.`); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to add student."); } };
  const updateTeam = async (event: React.FormEvent) => { event.preventDefault(); if (!selected || !team || updatedTeamName.trim().length < 2) return; try { setTeam(await updateMyTeam(selected.id, team.id, updatedTeamName.trim())); setMessage("Team details updated successfully."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Unable to update team."); } };
  if (loading) return <div className="page"><Loading label="Loading hackathon workspace..." /></div>;
  if (error) return <div className="page"><StatusState type="error" message={error} /></div>;
  if (!selected) return <div className="page"><StatusState type="empty" message="No hackathons are available yet." /></div>;
  return <div className="page"><p className="eyebrow">Student hackathon workspace</p><h1 className="title mt-1">{selected.name}</h1><p className="muted mt-2">Create your team, invite classmates, and track your hackathon progress.</p><label className="mt-5 block max-w-md"><span className="mb-1.5 block text-sm font-semibold">Hackathon</span><select className="input" value={selectedId} onChange={(event) => void switchHackathon(event.target.value)}>{hackathons.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
  <div className="mt-6 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card className="p-6"><p className="eyebrow">Hackathon details</p><h2 className="mt-2 text-xl font-bold">{selected.theme || "AI and Data Science challenge"}</h2><p className="muted mt-2">{selected.description || "Build, learn, and compete with your campus team."}</p><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><div className="flex items-center gap-2"><CalendarDays size={16} />{selected.startDate} to {selected.endDate}</div><div className="flex items-center gap-2"><Users size={16} />Teams: {selected.minTeamSize}-{selected.maxTeamSize}</div><div className="flex items-center gap-2"><MapPin size={16} />Campus venue</div></div></Card><Card className="p-6"><p className="eyebrow">Your team status</p>{team ? <><h2 className="mt-2 text-xl font-bold">{team.teamName}</h2><p className="muted mt-1">{team.status} · Position {team.position || "Pending"}</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="muted">Members</p><p className="mt-1 text-2xl font-bold">{team.teamMembers.length}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="muted">Score</p><p className="mt-1 text-2xl font-bold">{team.score}</p></div></div></> : <form className="mt-4 space-y-3" onSubmit={(event) => void createTeam(event)}><input className="input" value={teamName} onChange={(event) => setTeamName(event.target.value)} placeholder="Team name" required /><button className="btn-primary" type="submit"><Plus size={16} />Create team</button></form>}</Card></div>
    {team && <Card className="mt-5 p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Team members</p><h2 className="mt-1 text-xl font-bold">{team.teamName}</h2></div><div className="flex flex-wrap gap-2"><form className="flex gap-2" onSubmit={updateTeam}><input className="input max-w-xs" value={updatedTeamName} onChange={(event) => setUpdatedTeamName(event.target.value)} placeholder="Update team name" /><button type="submit" className="btn-secondary"><Save size={16} />Update</button></form><div className="flex gap-2"><input className="input max-w-xs" value={studentSearch} onChange={(event) => setStudentSearch(event.target.value)} placeholder="Roll number or name" /><button type="button" className="btn-secondary" onClick={() => void addMember()}><Search size={16} />Add student</button></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{team.teamMembers.map((member) => <div key={member.id} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold">{member.name}</p><p className="muted mt-1">{member.rollNumber}</p><p className="mt-2 text-xs font-semibold text-cyan-600">{member.role} · {member.position}</p></div>)}</div></Card>}
    {message && <p className="mt-4 text-sm font-semibold" role="status">{message}</p>}
    <div className="mt-8"><p className="eyebrow">Judging panel</p><h2 className="mt-1 text-xl font-bold">Meet your judges</h2><div className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{judges.length ? judges.map((judge) => <ProfileCard key={judge.id} name={judge.name} title={judge.expertise} handle={judge.handle} avatarUrl={judge.photo || ""} contactText="" />) : <StatusState type="empty" message="The judging panel has not been published yet." />}</div></div>
  </div>;
}
