import { Children, useState, type ReactNode } from "react";
import { AnimatePresence, motion } from "motion/react";
import "./Stepper.css";

export function Step({ children }: { children: ReactNode }) { return <div className="stepper-content">{children}</div>; }
type StepperProps = { children: ReactNode; initialStep?: number; onStepChange?: (step: number) => void; onFinalStepCompleted?: () => void; canAdvance?: (step: number) => boolean; backButtonText?: string; nextButtonText?: string };

export default function Stepper({ children, initialStep = 1, onStepChange = () => undefined, onFinalStepCompleted = () => undefined, canAdvance = () => true, backButtonText = "Previous", nextButtonText = "Next" }: StepperProps) {
  const steps = Children.toArray(children); const [current, setCurrent] = useState(initialStep); const [direction, setDirection] = useState(1); const [validationError, setValidationError] = useState(""); const completed = current > steps.length;
  const update = (next: number) => { setCurrent(next); if (next > steps.length) onFinalStepCompleted(); else onStepChange(next); };
  const go = (next: number) => { if (next > current && !canAdvance(current)) { setValidationError("Complete this step before continuing."); return; } setValidationError(""); setDirection(next > current ? 1 : -1); update(next); };
  return <div className="stepper"><div className="stepper-indicators">{steps.map((_, index) => { const number = index + 1; return <button key={number} type="button" className={`stepper-indicator ${current === number ? "active" : current > number ? "complete" : ""}`} onClick={() => go(number)} aria-label={`Go to step ${number}`}><span>{current > number ? "✓" : number}</span></button>; })}</div><div className="stepper-line"><span style={{ width: `${Math.max(0, Math.min(100, ((current - 1) / Math.max(steps.length - 1, 1)) * 100))}%` }} /></div><div className="stepper-panel">{!completed && <AnimatePresence mode="wait" initial={false} custom={direction}><motion.div key={current} custom={direction} initial={{ opacity: 0, x: direction * 24 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: direction * -24 }} transition={{ duration: .2 }}>{steps[current - 1]}</motion.div></AnimatePresence>}{validationError && <p className="stepper-error" role="alert">{validationError}</p>}</div>{!completed && <div className="stepper-actions"><button type="button" className="btn-secondary" onClick={() => go(current - 1)} disabled={current === 1}>{backButtonText}</button><button type="button" className="btn-primary" onClick={() => go(current === steps.length ? steps.length + 1 : current + 1)}>{current === steps.length ? "Generate teams" : nextButtonText}</button></div>}{completed && <div className="stepper-complete"><strong>Teams generated</strong><span>Your configuration is ready for review.</span><button type="button" className="btn-secondary" onClick={() => { setCurrent(1); setValidationError(""); }}>Start again</button></div>}</div>;
}
