import { useEffect, useRef, type CSSProperties } from "react";
import { Mesh, Program, Renderer, Triangle } from "ogl";
import "./Strands.css";

type StrandsProps = { colors?: string[]; count?: number; speed?: number; amplitude?: number; waviness?: number; thickness?: number; glow?: number; taper?: number; spread?: number; intensity?: number; saturation?: number; opacity?: number; scale?: number; className?: string };
const vertex = `#version 300 es
in vec2 position;
void main(){gl_Position=vec4(position,0.0,1.0);}`;
const fragment = `#version 300 es
precision highp float;
uniform float uTime,uSpeed,uAmplitude,uWaviness,uThickness,uGlow,uTaper,uSpread,uIntensity,uSaturation,uOpacity,uScale;
uniform vec2 uResolution; uniform vec3 uColors[4]; uniform int uCount; out vec4 fragColor;
const float PI=3.14159265;
void main(){vec2 uv=(gl_FragCoord.xy-.5*uResolution)/uResolution.y/uScale;float env=pow(max(cos(uv.x*PI*1.3),0.0),uTaper);vec3 col=vec3(0.0);for(int i=0;i<4;i++){if(i>=uCount)break;float fi=float(i);float t=uTime*uSpeed;float wave=sin(uv.x*(2.0+fi*.35)*uWaviness+t*(1.4+fi*1.2)+fi*1.7*uSpread)*.6+sin(uv.x*(2.2+fi*.38)*uWaviness-t*(1.0+fi*.8)+fi*2.9)*.4;float y=wave*(.1+.02*uIntensity)*env*uAmplitude;float thick=(.001+.05*uIntensity)*(.35+env)*uThickness;float g=thick/(abs(uv.y-y)+thick*.45);col+=uColors[i]*g*g*env;}col*=.45+.7*uIntensity;col=1.0-exp(-col*uGlow);float gray=dot(col,vec3(.2126,.7152,.0722));col=max(mix(vec3(gray),col,uSaturation),0.0);float lum=max(max(col.r,col.g),col.b);fragColor=vec4(col*uOpacity,lum*uOpacity);}`;
const rgb = (hex: string) => { const value = parseInt(hex.replace("#", ""), 16); return [(value >> 16 & 255) / 255, (value >> 8 & 255) / 255, (value & 255) / 255]; };

export default function Strands({ colors = ["#06b6d4", "#7c3aed", "#f97316"], count = 3, speed = .35, amplitude = 1, waviness = 1, thickness = .5, glow = 2.2, taper = 3, spread = 1, intensity = .55, saturation = 1.35, opacity = .16, scale = 1.5, className = "" }: StrandsProps) {
  const ref = useRef<HTMLDivElement>(null);
  const props = useRef({ colors, count, speed, amplitude, waviness, thickness, glow, taper, spread, intensity, saturation, opacity, scale });
  props.current = { colors, count, speed, amplitude, waviness, thickness, glow, taper, spread, intensity, saturation, opacity, scale };
  useEffect(() => { const container = ref.current; if (!container) return; const renderer = new Renderer({ webgl: 2, alpha: true, antialias: true, dpr: Math.min(devicePixelRatio || 1, 2) }); const gl = renderer.gl; gl.clearColor(0, 0, 0, 0); gl.enable(gl.BLEND); gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA); const program = new Program(gl, { vertex, fragment, uniforms: { uTime: { value: 0 }, uResolution: { value: new Float32Array([1, 1]) }, uColors: { value: [0, 1, 2, 3].map((i) => new Float32Array(rgb(colors[i] || colors[colors.length - 1] || "#ffffff"))) }, uCount: { value: Math.min(count, 4) }, uSpeed: { value: speed }, uAmplitude: { value: amplitude }, uWaviness: { value: waviness }, uThickness: { value: thickness }, uGlow: { value: glow }, uTaper: { value: taper }, uSpread: { value: spread }, uIntensity: { value: intensity }, uSaturation: { value: saturation }, uOpacity: { value: opacity }, uScale: { value: scale } } }); const mesh = new Mesh(gl, { geometry: new Triangle(gl), program }); container.appendChild(gl.canvas); gl.canvas.style.cssText = "display:block;width:100%;height:100%"; const resize = () => { const rect = container.getBoundingClientRect(); renderer.setSize(Math.max(1, rect.width), Math.max(1, rect.height)); const resolution = program.uniforms.uResolution.value as Float32Array; resolution[0] = gl.drawingBufferWidth; resolution[1] = gl.drawingBufferHeight; }; const observer = new ResizeObserver(resize); observer.observe(container); resize(); let frame = 0; const loop = (time: number) => { const current = props.current; program.uniforms.uTime.value = time * .001; program.uniforms.uCount.value = Math.min(Math.max(Math.round(current.count), 1), 4); program.uniforms.uSpeed.value = current.speed; program.uniforms.uAmplitude.value = current.amplitude; program.uniforms.uWaviness.value = current.waviness; program.uniforms.uThickness.value = current.thickness; program.uniforms.uGlow.value = current.glow; program.uniforms.uTaper.value = current.taper; program.uniforms.uSpread.value = current.spread; program.uniforms.uIntensity.value = current.intensity; program.uniforms.uSaturation.value = current.saturation; program.uniforms.uOpacity.value = current.opacity; program.uniforms.uScale.value = current.scale; renderer.render({ scene: mesh }); frame = requestAnimationFrame(loop); }; frame = requestAnimationFrame(loop); return () => { cancelAnimationFrame(frame); observer.disconnect(); if (gl.canvas.parentNode === container) container.removeChild(gl.canvas); gl.getExtension("WEBGL_lose_context")?.loseContext(); }; }, []);
  return <div ref={ref} className={`strands-container ${className}`.trim()} aria-hidden="true" style={{ "--strand-opacity": opacity } as CSSProperties} />;
}
